
export const actions = {
    FETCH_BANKS: "FETCH_BANKS",
    SET_ID: "SET_ID",
    SET_BANK_TO_EDIT_MODAL: "SET_BANK_TO_EDIT_MODAL",
    GET_ALL_BANKS_NAMES: "GET_ALL_BANKS_NAMES",
    SET_SELECTED_BANK: "SET_SELECTED_BANK",
    SET_MONTHLY_PAYMENT: "SET_MONTHLY_PAYMENT"
}